### ISSUE TITLE
💎 Copilot and Gemini chat should be disallowed/blocked

### ISSUE THREAD

**Issue by patrik1katai** [balazsgerlei/SecureWebView#1]
Was able to breakout of the Secure WebView sample app by navigating through to Copilot on Microsoft, or to Gemini on Google.
From there (after logging in) on Copilot I was able to reach other search engines like Brave. On Gemini links are redacted from chat, but there is still a Google button that searches on Google and lets you open suggestion links to the search results page.

I think these AI chats should be added to the disallowed list and maybe some other popular ones that could be reachable through socials.

**Comment by balazsgerlei** [comment]
I can look it up, but even for confirmation can you write down the URLs for the AI chatbots you've encountered? Thanks!

**Comment by patrik1katai** [comment]
Here are the URLs for the ones I could reach:
https://gemini.google.com/
https://copilot.microsoft.com/
